apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: client
  template:
    metadata:
      annotations:
        prometheus.io/port: "3200"
    spec:
      containers:
        - name: app
          image: app
          ports:
            - name: http
              containerPort: 3200
          env:
            - name: PORT
              value: "3200"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
