/**
 * @file snapchatWebhookProcessor.test.ts
 * @description Unit tests for SnapchatWebhookProcessor — synthetic webhook events
 *              generated by internal polling workers for creative status changes.
 * @layer test
 */

import { describe, it, beforeAll, expect } from "vitest";
import assert from "node:assert/strict";
import { createHmac } from "crypto";
import { SnapchatWebhookProcessor } from "../../../src/webhooks/processors/snapchatWebhookProcessor.js";

// ===========================
// Test Helpers
// ===========================

function generateHmacSignature(payload: string, secret: string): string {
  return createHmac("sha256", secret).update(payload, "utf8").digest("hex");
}

// ===========================
// Signature Verification Tests (5 tests)
// ===========================

describe("SnapchatWebhookProcessor - Signature Verification", () => {
  let processor: SnapchatWebhookProcessor;
  const testSecret = "test-snapchat-internal-secret";

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should verify valid signature with sha256= prefix", () => {
    const payload = JSON.stringify({ eventType: "CREATIVE_APPROVED" });
    const signature = generateHmacSignature(payload, testSecret);

    const isValid = processor.verify(payload, `sha256=${signature}`, testSecret);
    expect(isValid).toBe(true);
  });

  it("should verify valid signature without sha256= prefix", () => {
    const payload = JSON.stringify({ eventType: "CREATIVE_APPROVED" });
    const signature = generateHmacSignature(payload, testSecret);

    const isValid = processor.verify(payload, signature, testSecret);
    expect(isValid).toBe(true);
  });

  it("should reject invalid signature", () => {
    const payload = JSON.stringify({ eventType: "CREATIVE_APPROVED" });

    const isValid = processor.verify(payload, "sha256=invalid-sig", testSecret);
    expect(isValid).toBe(false);
  });

  it("should reject signature with wrong secret", () => {
    const payload = JSON.stringify({ eventType: "CREATIVE_APPROVED" });
    const signature = generateHmacSignature(payload, "wrong-secret");

    const isValid = processor.verify(payload, signature, testSecret);
    expect(isValid).toBe(false);
  });

  it("should return false for missing signature", () => {
    const payload = JSON.stringify({ eventType: "CREATIVE_APPROVED" });

    const isValid = processor.verify(payload, "", testSecret);
    expect(isValid).toBe(false);
  });
});

// ===========================
// CREATIVE_APPROVED Event Parsing Tests (3 tests)
// ===========================

describe("SnapchatWebhookProcessor - CREATIVE_APPROVED Event Parsing", () => {
  let processor: SnapchatWebhookProcessor;

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should parse CREATIVE_APPROVED event and map to POST_PUBLISHED", async () => {
    const payload = {
      eventType: "CREATIVE_APPROVED",
      creativeId: "creative-001",
      adAccountId: "adaccount-123",
      reviewStatus: "APPROVED",
      timestamp: "2024-06-15T10:00:00Z",
      internalEventId: "evt-aaa",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.eventType, "POST_PUBLISHED");
    assert.strictEqual(result.normalizedData.eventType, "CREATIVE_APPROVED");
    assert.strictEqual(result.normalizedData.creativeId, "creative-001");
    assert.strictEqual(result.normalizedData.adAccountId, "adaccount-123");
    assert.strictEqual(result.normalizedData.reviewStatus, "APPROVED");
    assert.strictEqual(result.normalizedData.timestamp, "2024-06-15T10:00:00Z");
    assert.strictEqual(result.normalizedData.internalEventId, "evt-aaa");
  });

  it("should not include reviewStatusReasons when absent", async () => {
    const payload = {
      eventType: "CREATIVE_APPROVED",
      creativeId: "creative-002",
      adAccountId: "adaccount-456",
      reviewStatus: "APPROVED",
      timestamp: "2024-06-15T11:00:00Z",
      internalEventId: "evt-bbb",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    expect(result.normalizedData).not.toHaveProperty("reviewStatusReasons");
  });

  it("should resolve related entities structure", async () => {
    const payload = {
      eventType: "CREATIVE_APPROVED",
      creativeId: "creative-003",
      adAccountId: "adaccount-789",
      reviewStatus: "APPROVED",
      timestamp: "2024-06-15T12:00:00Z",
      internalEventId: "evt-ccc",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    expect(result).toHaveProperty("relatedEntities");
    expect(typeof result.relatedEntities).toBe("object");
  });
});

// ===========================
// CREATIVE_REJECTED Event Parsing Tests (3 tests)
// ===========================

describe("SnapchatWebhookProcessor - CREATIVE_REJECTED Event Parsing", () => {
  let processor: SnapchatWebhookProcessor;

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should parse CREATIVE_REJECTED event and map to API_ERROR", async () => {
    const payload = {
      eventType: "CREATIVE_REJECTED",
      creativeId: "creative-rej-001",
      adAccountId: "adaccount-rej",
      reviewStatus: "REJECTED",
      reviewStatusReasons: ["Violates community guidelines", "Misleading content"],
      timestamp: "2024-06-15T14:00:00Z",
      internalEventId: "evt-rej-1",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.eventType, "API_ERROR");
    assert.strictEqual(result.normalizedData.eventType, "CREATIVE_REJECTED");
    assert.strictEqual(result.normalizedData.creativeId, "creative-rej-001");
    assert.strictEqual(result.normalizedData.reviewStatus, "REJECTED");
  });

  it("should include reviewStatusReasons when present", async () => {
    const reasons = ["Policy violation", "Low quality"];
    const payload = {
      eventType: "CREATIVE_REJECTED",
      creativeId: "creative-rej-002",
      adAccountId: "adaccount-rej2",
      reviewStatus: "REJECTED",
      reviewStatusReasons: reasons,
      timestamp: "2024-06-15T15:00:00Z",
      internalEventId: "evt-rej-2",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    expect(result.normalizedData.reviewStatusReasons).toStrictEqual(reasons);
  });

  it("should handle rejection without reasons", async () => {
    const payload = {
      eventType: "CREATIVE_REJECTED",
      creativeId: "creative-rej-003",
      adAccountId: "adaccount-rej3",
      reviewStatus: "REJECTED",
      timestamp: "2024-06-15T16:00:00Z",
      internalEventId: "evt-rej-3",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.eventType, "API_ERROR");
    expect(result.normalizedData).not.toHaveProperty("reviewStatusReasons");
  });
});

// ===========================
// CREATIVE_PROCESSING Event Parsing Tests (2 tests)
// ===========================

describe("SnapchatWebhookProcessor - CREATIVE_PROCESSING Event Parsing", () => {
  let processor: SnapchatWebhookProcessor;

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should parse CREATIVE_PROCESSING event and map to VIDEO_PROCESSED", async () => {
    const payload = {
      eventType: "CREATIVE_PROCESSING",
      creativeId: "creative-proc-001",
      adAccountId: "adaccount-proc",
      reviewStatus: "PENDING_REVIEW",
      timestamp: "2024-06-15T17:00:00Z",
      internalEventId: "evt-proc-1",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.eventType, "VIDEO_PROCESSED");
    assert.strictEqual(result.normalizedData.eventType, "CREATIVE_PROCESSING");
    assert.strictEqual(result.normalizedData.creativeId, "creative-proc-001");
  });

  it("should include all normalized fields for processing event", async () => {
    const payload = {
      eventType: "CREATIVE_PROCESSING",
      creativeId: "creative-proc-002",
      adAccountId: "adaccount-proc2",
      reviewStatus: "IN_REVIEW",
      timestamp: "2024-06-15T18:00:00Z",
      internalEventId: "evt-proc-2",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.normalizedData.adAccountId, "adaccount-proc2");
    assert.strictEqual(result.normalizedData.reviewStatus, "IN_REVIEW");
    assert.strictEqual(result.normalizedData.internalEventId, "evt-proc-2");
  });
});

// ===========================
// Error Handling Tests (4 tests)
// ===========================

describe("SnapchatWebhookProcessor - Error Handling", () => {
  let processor: SnapchatWebhookProcessor;

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should throw error for missing eventType", async () => {
    const payload = {
      creativeId: "creative-no-event",
      adAccountId: "adaccount-err",
    };

    await expect(processor.parse(payload as unknown as Record<string, unknown>)).rejects.toThrow(
      "Invalid Snapchat webhook: missing eventType or creativeId"
    );
  });

  it("should throw error for missing creativeId", async () => {
    const payload = {
      eventType: "CREATIVE_APPROVED",
      adAccountId: "adaccount-err2",
    };

    await expect(processor.parse(payload as unknown as Record<string, unknown>)).rejects.toThrow(
      "Invalid Snapchat webhook: missing eventType or creativeId"
    );
  });

  it("should throw error for completely empty payload", async () => {
    const payload = {};

    await expect(processor.parse(payload as unknown as Record<string, unknown>)).rejects.toThrow(
      "Invalid Snapchat webhook: missing eventType or creativeId"
    );
  });

  it("should default to POST_UPDATED for unknown event type", async () => {
    const payload = {
      eventType: "UNKNOWN_EVENT_TYPE",
      creativeId: "creative-unknown",
      adAccountId: "adaccount-unknown",
      reviewStatus: "UNKNOWN",
      timestamp: "2024-06-15T19:00:00Z",
      internalEventId: "evt-unknown",
    };

    const result = await processor.parse(payload as unknown as Record<string, unknown>);

    assert.strictEqual(result.eventType, "POST_UPDATED");
  });
});

// ===========================
// Process Method Tests (3 tests)
// ===========================

describe("SnapchatWebhookProcessor - Process", () => {
  let processor: SnapchatWebhookProcessor;

  beforeAll(() => {
    processor = new SnapchatWebhookProcessor();
  });

  it("should process CREATIVE_APPROVED without throwing", async () => {
    const normalizedData = { eventType: "CREATIVE_APPROVED", creativeId: "c-1" };
    const relatedEntities = { postId: "post-1", channelId: "ch-1" };

    await expect(processor.process(normalizedData, relatedEntities)).resolves.not.toThrow();
  });

  it("should process CREATIVE_REJECTED without throwing", async () => {
    const normalizedData = {
      eventType: "CREATIVE_REJECTED",
      creativeId: "c-2",
      reviewStatusReasons: ["bad content"],
    };
    const relatedEntities = { postId: "post-2", channelId: "ch-2" };

    await expect(processor.process(normalizedData, relatedEntities)).resolves.not.toThrow();
  });

  it("should process CREATIVE_PROCESSING without throwing", async () => {
    const normalizedData = { eventType: "CREATIVE_PROCESSING", creativeId: "c-3" };
    const relatedEntities = { postId: "post-3", channelId: "ch-3" };

    await expect(processor.process(normalizedData, relatedEntities)).resolves.not.toThrow();
  });
});

// Total: 20 tests covering Snapchat webhook processor functionality
