/**
 * @file snapchatWebhookProcessor.ts
 * @description Snapchat Webhook Processor.
 *              Snapchat does NOT support native webhooks. This processor handles
 *              polling-based creative status change notifications that are generated
 *              internally by OmniPost workers polling the Snapchat Ads API.
 *
 * The worker periodically calls GET /v1/adaccounts/{id}/creatives and checks
 * review_status changes (PENDING_REVIEW → APPROVED / REJECTED).
 * When a status change is detected, the worker creates a synthetic webhook event
 * that this processor handles.
 *
 * Synthetic event types:
 * - CREATIVE_APPROVED: Creative was approved by Snapchat review
 * - CREATIVE_REJECTED: Creative was rejected (includes rejection reasons)
 * - CREATIVE_PROCESSING: Creative is being processed
 * @layer infrastructure
 */

import type { WebhookEventType } from "@infra/prisma";
import type { ProviderName } from "@shared/types";
import { prisma } from "@infra/prisma";
import { webhookLogger } from "../../lib/logger.js";
import { AppError } from "../../lib/errors/AppError.js";
import { AbstractWebhookProcessor } from "./AbstractWebhookProcessor.js";

/**
 * Snapchat synthetic webhook payload (generated by OmniPost polling worker)
 */
interface SnapchatCreativeStatusPayload {
  eventType: "CREATIVE_APPROVED" | "CREATIVE_REJECTED" | "CREATIVE_PROCESSING";
  creativeId: string;
  adAccountId: string;
  reviewStatus: string;
  reviewStatusReasons?: string[];
  timestamp: string;
  internalEventId: string;
}

/**
 * Snapchat Webhook Processor
 *
 * Handles synthetic webhook events generated by internal polling workers.
 * Since Snapchat has no native webhook API, this processor is designed
 * to work with internally-generated events from creative status polling.
 */
export class SnapchatWebhookProcessor extends AbstractWebhookProcessor {
  protected override providerId: ProviderName = "SNAPCHAT";
  protected override signaturePrefix = "sha256=";
  protected override signatureEncoding: "hex" | "base64" = "hex";

  /**
   * @method verify
   * @description Verifies synthetic webhook signature.
   *              Since these are internal events, verification uses a shared internal secret.
   */
  override verify(
    payload: string,
    signature: string,
    secret: string,
    _headers?: Record<string, string>
  ): boolean {
    return super.verify(payload, signature, secret);
  }

  /**
   * @method parse
   * @description Parses Snapchat creative status change payload.
   */
  override async parse(payload: Record<string, unknown>): Promise<{
    eventType: WebhookEventType;
    normalizedData: Record<string, unknown>;
    relatedEntities: {
      accountId?: string;
      projectId?: string;
      postId?: string;
      channelId?: string;
    };
  }> {
    const typedPayload = payload as unknown as SnapchatCreativeStatusPayload;

    if (!typedPayload.eventType || !typedPayload.creativeId) {
      throw AppError.badRequest("Invalid Snapchat webhook: missing eventType or creativeId");
    }

    const eventType = this.mapSnapchatEvent(typedPayload.eventType);
    const normalizedData = this.normalizePayload(typedPayload);
    const relatedEntities = await this.findRelatedEntities(typedPayload);

    return { eventType, normalizedData, relatedEntities };
  }

  /**
   * @method process
   * @description Processes a Snapchat creative status change.
   */
  override async process(
    normalizedData: Record<string, unknown>,
    relatedEntities: {
      accountId?: string;
      projectId?: string;
      postId?: string;
      channelId?: string;
    }
  ): Promise<void> {
    const eventType = normalizedData.eventType as string;

    switch (eventType) {
      case "CREATIVE_APPROVED":
        await this.handleCreativeApproved(normalizedData, relatedEntities);
        break;
      case "CREATIVE_REJECTED":
        await this.handleCreativeRejected(normalizedData, relatedEntities);
        break;
      case "CREATIVE_PROCESSING":
        webhookLogger.info(
          { creativeId: normalizedData.creativeId, postId: relatedEntities.postId },
          "Snapchat creative is being processed"
        );
        break;
      default:
        webhookLogger.warn({ event: eventType }, "Unknown Snapchat event type");
    }
  }

  /**
   * Maps Snapchat event types to OmniPost WebhookEventType
   */
  private mapSnapchatEvent(snapchatEvent: string): WebhookEventType {
    switch (snapchatEvent) {
      case "CREATIVE_APPROVED":
        return "POST_PUBLISHED";
      case "CREATIVE_REJECTED":
        return "API_ERROR";
      case "CREATIVE_PROCESSING":
        return "VIDEO_PROCESSED";
      default:
        return "POST_UPDATED";
    }
  }

  /**
   * Normalizes Snapchat creative status payload
   */
  private normalizePayload(payload: SnapchatCreativeStatusPayload): Record<string, unknown> {
    return {
      eventType: payload.eventType,
      creativeId: payload.creativeId,
      adAccountId: payload.adAccountId,
      reviewStatus: payload.reviewStatus,
      ...(payload.reviewStatusReasons ? { reviewStatusReasons: payload.reviewStatusReasons } : {}),
      timestamp: payload.timestamp,
      internalEventId: payload.internalEventId,
    };
  }

  /**
   * Finds related OmniPost entities from Snapchat creative data
   */
  private async findRelatedEntities(_payload: SnapchatCreativeStatusPayload): Promise<{
    accountId?: string;
    projectId?: string;
    postId?: string;
    channelId?: string;
  }> {
    try {
      const channel = await prisma.channel.findFirst({
        where: {
          provider: "SNAPCHAT",
          deletedAt: null,
        },
      });

      if (!channel) return {};

      const project = await prisma.project.findUnique({
        where: { id: channel.projectId },
      });

      const result: {
        accountId?: string;
        projectId?: string;
        postId?: string;
        channelId?: string;
      } = {
        channelId: channel.id,
        projectId: channel.projectId,
        ...(project ? { accountId: project.accountId } : {}),
      };

      // Try to find the post via publish log
      const publishLog = await prisma.publishLog.findFirst({
        where: {
          channelId: channel.id,
          status: "OK",
        },
        orderBy: { createdAt: "desc" },
      });

      if (publishLog?.postId) {
        result.postId = publishLog.postId;
      }

      return result;
    } catch (error: unknown) {
      webhookLogger.error({ error }, "Failed to find related entities for Snapchat webhook");
      return {};
    }
  }

  /**
   * Handles creative approval — broadcasts post status update
   */
  private async handleCreativeApproved(
    normalizedData: Record<string, unknown>,
    relatedEntities: { postId?: string; channelId?: string }
  ): Promise<void> {
    webhookLogger.info(
      {
        creativeId: normalizedData.creativeId,
        postId: relatedEntities.postId,
      },
      "Snapchat creative approved"
    );

    if (relatedEntities.postId) {
      this.broadcastPostStatusChange(relatedEntities.postId, "PUBLISHED", {
        creativeId: normalizedData.creativeId,
        reviewStatus: "APPROVED",
      });
    }
  }

  /**
   * Handles creative rejection — logs reason and broadcasts error
   */
  private async handleCreativeRejected(
    normalizedData: Record<string, unknown>,
    relatedEntities: { postId?: string; channelId?: string }
  ): Promise<void> {
    const reasons = normalizedData.reviewStatusReasons as string[] | undefined;

    webhookLogger.warn(
      {
        creativeId: normalizedData.creativeId,
        postId: relatedEntities.postId,
        reasons,
      },
      "Snapchat creative rejected"
    );

    if (relatedEntities.postId) {
      this.broadcastPostStatusChange(relatedEntities.postId, "FAILED", {
        creativeId: normalizedData.creativeId,
        reviewStatus: "REJECTED",
        ...(reasons ? { reasons } : {}),
      });
    }
  }
}
