/**
 * @file generate-api-types.ts
 * @description Generador de tipos TypeScript desde el spec OpenAPI emitido
 *   por Fastify (`@fastify/swagger`).
 *
 *   Pipeline:
 *     1. Invoca `pnpm --filter @apps/api dump:openapi` que bootea `createApp()`,
 *        dumpea `app.swagger()` a `/tmp/omnipost-openapi.json`, y cierra.
 *     2. Invoca `pnpm exec openapi-ts` (config en root: `openapi-ts.config.ts`)
 *        que lee el spec dumped y genera tipos a
 *        `packages/shared/src/api-generated/`.
 *
 *   Uso:
 *     pnpm generate:api-types
 *
 *   Precondición: PostgreSQL + Redis up (porque `createApp()` se conecta
 *   en su path normal). En local: `pnpm db:up`. En CI: las services del
 *   job test ya proveen ambos.
 *
 *   Re-generar tras cada cambio de schema en una ruta migrada. §3.1.b
 *   agregará un gate de drift en CI que falla si los archivos committed
 *   no coinciden con la regen.
 *
 *   Workstream: §3.1 Normalization Roadmap.
 *
 * @layer infrastructure
 */
import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const OUTPUT_DIR = path.join(REPO_ROOT, "packages/shared/src/api-generated");

function runSubprocess(label: string, args: string[]): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const child = spawn("pnpm", args, {
      cwd: REPO_ROOT,
      stdio: "inherit",
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${label} exited with code ${code}`));
    });
  });
}

/**
 * Post-process: prepend canon JSDoc header to each generated file. Required by
 * CLAUDE.md §Documentation ("Every file gets a JSDoc header — no exceptions");
 * the Stop hook enforces it. The header is preserved across regenerations
 * because we re-prepend it here every run.
 */
function applyCanonHeader(): void {
  const files = readdirSync(OUTPUT_DIR).filter((f) => f.endsWith(".ts"));
  for (const file of files) {
    const filePath = path.join(OUTPUT_DIR, file);
    const body = readFileSync(filePath, "utf-8");
    if (body.startsWith("/**\n * @file ")) continue; // already headered
    const header = [
      "/**",
      ` * @file ${file}`,
      " * @description AUTO-GENERATED por @hey-api/openapi-ts a partir del spec",
      " *   OpenAPI emitido por Fastify (`@fastify/swagger`). NO editar a mano.",
      " *   Regenerar con `pnpm generate:api-types`.",
      " *   Workstream: §3.1 Normalization Roadmap.",
      " * @layer infrastructure",
      " */",
      "",
    ].join("\n");
    // Strip the legacy auto-gen line if present.
    const cleaned = body.replace(
      /^\/\/ This file is auto-generated by @hey-api\/openapi-ts\n+/,
      ""
    );
    writeFileSync(filePath, header + cleaned);
  }
}

/**
 * Post-process: NodeNext requires an explicit `.js` extension on relative
 * import/export specifiers. @hey-api emits extensionless paths, so add `.js`
 * here to match the package's NodeNext tsc build, which resolves
 * `./types.gen.js` (not `./types.gen`). Idempotent: paths that already carry an
 * extension are left untouched, so a fresh regeneration is byte-identical to
 * the committed copy and the CI drift gate stays green.
 */
function applyJsExtensions(): void {
  const files = readdirSync(OUTPUT_DIR).filter((f) => f.endsWith(".ts"));
  for (const file of files) {
    const filePath = path.join(OUTPUT_DIR, file);
    const body = readFileSync(filePath, "utf-8");
    const fixed = body.replace(
      /(\bfrom\s+")(\.\.?\/[^"]+?)(")/g,
      (full, pre: string, spec: string, post: string) =>
        /\.(js|json|css)$/.test(spec) ? full : `${pre}${spec}.js${post}`
    );
    if (fixed !== body) writeFileSync(filePath, fixed);
  }
}

async function main() {
  await runSubprocess("dump:openapi", ["--filter", "@apps/api", "dump:openapi"]);
  await runSubprocess("openapi-ts", ["exec", "openapi-ts"]);
  applyCanonHeader();

  // Homologate formatting with the pre-commit hook: lint-staged runs
  // `eslint --fix` then `prettier --write` on staged *.ts. Applying the SAME
  // tools in the SAME order here writes the generated files in their final
  // committed form, so committing them is a no-op AND a fresh regeneration is
  // byte-identical to the committed copy — i.e. the CI drift gate is idempotent.
  await runSubprocess("eslint", ["exec", "eslint", "--fix", "packages/shared/src/api-generated"]);
  await runSubprocess("prettier", [
    "exec",
    "prettier",
    "--write",
    "packages/shared/src/api-generated",
  ]);

  // Re-apply .js extensions last so neither eslint --fix nor prettier --write
  // can strip them; this is the form the NodeNext build + committed copy expect.
  applyJsExtensions();

  console.log("✓ Types generated at packages/shared/src/api-generated/");
}

main().catch((err) => {
  console.error("❌ generate-api-types failed:", err);
  process.exit(1);
});
