apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-post

resources:
  - ../../base/templates/deployment.yaml
  - ../../base/templates/hpa.yaml

namePrefix: workers-

commonLabels:
  app.kubernetes.io/component: workers
  app.kubernetes.io/part-of: backend

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: app
    newName: ghcr.io/omni-post/workers
    newTag: latest
