/**
 * @file navigation.ts
 * @description Locale-aware navigation primitives generated by next-intl.
 *              These wrappers (`Link`, `redirect`, `usePathname`,
 *              `useRouter`, `getPathname`) automatically prepend the active
 *              locale prefix, so callers navigate with plain paths
 *              (e.g. "/users") and the locale is preserved.
 * @layer infrastructure
 */
import { createNavigation } from "next-intl/navigation";
import { routing } from "./routing.js";

export const { Link, redirect, usePathname, useRouter, getPathname } = createNavigation(routing);
