import rootConfig from '../../stryker.config.mjs'
/** @type {import('@stryker-mutator/core').PartialStrykerOptions} */
export default {
  ...rootConfig,
  tsconfigFile: 'tsconfig.json',
  incrementalFile: 'reports/stryker-incremental-micro.json',
  htmlReporter: { fileName: 'reports/mutation/micro-E4.html' },
  vitest: { configFile: 'vitest.config.ts' },
  coverageAnalysis: 'perTest',
  checkers: [],
  plugins: ['@stryker-mutator/vitest-runner'],
  concurrency: 4,
  dryRunTimeoutMinutes: 15,
  mutate: [
    "src/application/crisis/**/*.ts",
    "src/application/aiPromptTemplates/**/*.ts",
    "src/application/external-notifications/**/*.ts",
    "src/application/apiKeys/**/*.ts",
    "src/application/ai-image/**/*.ts",
    "src/application/brand-voice/**/*.ts",
    "src/application/events/**/*.ts",
    "src/application/utm/**/*.ts",
    "src/application/usage/**/*.ts",
    "!src/application/crisis/**/*.test.ts",
    "!src/application/crisis/**/*.spec.ts",
    "!src/application/aiPromptTemplates/**/*.test.ts",
    "!src/application/aiPromptTemplates/**/*.spec.ts",
    "!src/application/external-notifications/**/*.test.ts",
    "!src/application/external-notifications/**/*.spec.ts",
    "!src/application/apiKeys/**/*.test.ts",
    "!src/application/apiKeys/**/*.spec.ts",
    "!src/application/ai-image/**/*.test.ts",
    "!src/application/ai-image/**/*.spec.ts",
    "!src/application/brand-voice/**/*.test.ts",
    "!src/application/brand-voice/**/*.spec.ts",
    "!src/application/events/**/*.test.ts",
    "!src/application/events/**/*.spec.ts",
    "!src/application/utm/**/*.test.ts",
    "!src/application/utm/**/*.spec.ts",
    "!src/application/usage/**/*.test.ts",
    "!src/application/usage/**/*.spec.ts"
],
  thresholds: { high: 80, low: 60, break: null },
}
