import rootConfig from '../../stryker.config.mjs'
/** @type {import('@stryker-mutator/core').PartialStrykerOptions} */
export default {
  ...rootConfig,
  tsconfigFile: 'tsconfig.json',
  incrementalFile: 'reports/stryker-incremental-micro.json',
  htmlReporter: { fileName: 'reports/mutation/micro-A7.html' },
  vitest: { configFile: 'vitest.config.ts' },
  coverageAnalysis: 'perTest',
  checkers: [],
  plugins: ['@stryker-mutator/vitest-runner'],
  concurrency: 4,
  dryRunTimeoutMinutes: 15,
  mutate: [
    "src/campaigns/**/*.ts",
    "src/notifications/**/*.ts",
    "src/reports/**/*.ts",
    "src/recurring/**/*.ts",
    "src/approvals/**/*.ts",
    "src/comments/**/*.ts",
    "src/team/**/*.ts",
    "src/links/**/*.ts",
    "!src/campaigns/**/*.test.ts",
    "!src/campaigns/**/*.spec.ts",
    "!src/notifications/**/*.test.ts",
    "!src/notifications/**/*.spec.ts",
    "!src/reports/**/*.test.ts",
    "!src/reports/**/*.spec.ts",
    "!src/recurring/**/*.test.ts",
    "!src/recurring/**/*.spec.ts",
    "!src/approvals/**/*.test.ts",
    "!src/approvals/**/*.spec.ts",
    "!src/comments/**/*.test.ts",
    "!src/comments/**/*.spec.ts",
    "!src/team/**/*.test.ts",
    "!src/team/**/*.spec.ts",
    "!src/links/**/*.test.ts",
    "!src/links/**/*.spec.ts"
],
  thresholds: { high: 80, low: 60, break: null },
}
